on:
  workflow_call:

jobs:
  run-linting:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the codebase
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install test dependencies
        run: pip3 install yamllint

      - name: Run yamllint
        run: yamllint .

      - name: Run ansible-lint
        uses: ansible/ansible-lint-action@v6.16.0
